name: deploy-service

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying NodeJS Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: deploying application to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY  }}
          HOSTNAME: ${{ secrets.HOST_DNS  }}
          USER_NAME: ${{ secrets.USERNAME  }}
          TARGET: ${{ secrets.TARGET_DIR }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} && cd TARGET && bash deploy/sync.sh